### ISSUE TITLE
Can not run the demo app

### ISSUE THREAD

**Issue by Jay-Liao** [postrational/rest_api_demo#10] opened 2020-03-10 10:37 UTC
I follow the steps in this article to setup demo application, but there is an error raised.
Traceback (most recent call last):
  File "rest_api_demo/app.py", line 6, in <module>
    from rest_api_demo.api.blog.endpoints.posts import ns as blog_posts_namespace
  File "d:\workspace\rest_api_demo\rest_api_demo\api\blog\endpoints\posts.py", line 4, in <module>
    from flask_restplus import Resource
  File "D:\workspace\rest_api_demo\.venv\lib\site-packages\flask_restplus\__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "D:\workspace\rest_api_demo\.venv\lib\site-packages\flask_restplus\fields.py", line 12, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (D:\workspace\rest_api_demo\.venv\lib\site-packages\werkzeug\__init__.py)

article: http://michal.karzynski.pl/blog/2016/06/19/building-beautiful-restful-apis-using-flask-swagger-ui-flask-restplus/

After investigation,
This error can be fixed by downgrading Werkzeug to version 0.16.0.

requirements.txt (before downgrading)
flask-restplus==0.9.2
Flask-SQLAlchemy==2.1

requirements.txt (after downgrading)
flask-restplus==0.9.2
Flask-SQLAlchemy==2.1
Werkzeug==0.16.0

**Comment by edeca** [comment] 2020-03-24 15:33
The root cause of this issue needs to be fixed in flask-restplus itself, see the bug: https://github.com/noirbizarre/flask-restplus/issues/777

**Comment by KleinerKobold** [comment] 2020-12-13 10:04
done a pull request for this

**Comment by postrational** [comment] 2021-01-23 20:00
I merged the PR which pins Werkzeug version.

**Closed as completed by postrational** 2021-01-23 20:00 UTC
